### PR TITLE
StringBuilder -> String_Builder and a couple other minor renames

### PR DESCRIPTION
**Pull request by Raelifin**
Addresses https://github.com/adamant/Adamant.Compiler/issues/28

Also in this PR: A minor change to saveVersion.sh, which I hadn't tested properly.

### CODE REVIEW

**Review by WalkerCodeRanger — CHANGES_REQUESTED** [review]
Looks like there is something wrong with your translated/previous/* files.  They appear to include the changes in the current version.  As if you ran saveVersion.sh after having built the new version.  Those files should reflect the version that was current before you started working.  Please submit a corrected commit.  (contact me if you need assistance on how to do that).

**Comment by Raelifin** [comment]
I'm confused. I did indeed do a saveVersion after building, but I thought that was necessary in order for the code to compile. The version before I started working doesn't have the types that I introduce, so it won't build.

Let me put another way. To rename StringBuilder to String_Builder, I need to:
1) Add a String_Builder class.
2) Compile the compiler with the new class.
3) Modify the references to StringBuilder to use the new String_Builder class, and remove the old StringBuilder class.
4) Compile the compiler to cease using the old class.

If I don't overwrite the translated/previous, how do I make the change?

**Comment by WalkerCodeRanger** [comment]
What you have to do is implement the feature in multiple steps over several commits.  This is easier when it is just an addition to the language or runtime library.  In that case, you add the feature to the language or runtime library without using it in the compiler yet. Then in future commits, you can use it in the compiler source.

In the case of a breaking changing to the language or runtime library, you have to make a change supporting both forms in the first commit, then in a subsequent commit, change the compiler to use the new form and remove support for the old one.

So for example, in the first commit support both StringBuilder and String_Builder without changing the compiler to use String_Builder yet.  This can probably be done with a C++ typedef to effectively give the class a second name.  Then in the second commit, change the compiler source to use String_Builder and remove support for StringBuilder.

I've created issue #33 to setup CI builds that will check that the compiler builds correctly with the previous version and can also self-build.  This should make it easy to not accidentally mess up.  Also, once that is done we can stop checking in the previous version.  Currently, the previous version would cause real problems for multi-branch development.  I will then set GitHub so that all pull request merges do a rebase.  This may require a little more complex when using git, but will produce an apparently straight line of development.  Otherwise, there could be issues with bootstrapping merge commits because there may be no previous version of the compiler that can build the merged code.

**Comment by WalkerCodeRanger** [comment]
These changes were reworked into a6370023427a69292f5ceba64d0ef7f50313edcc and 3e13243c119d954fd905c590c23f293c9d8206b1

**Pull request closed without merging**
